#!/bin/bash
# Bash script for starting all necessary daemons for app gateway


function stop_daemons() {
    echo "Stopping daemons"
    kill -TERM "$REST_PID" 
    kill -TERM "$API_PID" 
}

if [ "$1" == '/api/iptables-api' ]; then 
    echo "Starting daemons"
    trap 'stop_daemons' EXIT
    
    /api/iprouteRESt &
    export REST_PID=$!
    
    exec "$@" & 
    export API_PID=$! 
    
    wait $API_PID

else
    exec "$@"
fi

